#!/usr/bin/env bash
set -euo pipefail

# Block edits to build/ directory — these are generated artifacts.
# Also block edits to objdiff.json, report.json, etc.

input=$(cat)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .file_path // ""')

if [[ "$file_path" == *build/* ]]; then
    echo "BLOCKED: Files in build/ are auto-generated. Run the build to regenerate them." >&2
    exit 2
fi

if [[ "$file_path" == *objdiff.json ]] || [[ "$file_path" == *report.json ]]; then
    echo "BLOCKED: This file is auto-generated by the build tools." >&2
    exit 2
fi

exit 0
